import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './global.css';
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center ">
          <div className="w-[50%] flex flex-col items-center  lg:w-[80%] sm:w-[100%]  ">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
